### ISSUE TITLE
Use all images for evaluation ?

### ISSUE THREAD

**Issue by salvador-blanco** [tensorlayer/hyperpose#326]
By checking at the `evalu(model,dataset)` log I get the impression that not all the images are being used for the evaluation.

```
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
```
**evluating on total 29 images...**
```
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
```

Is it possible to use all the images in the eval folder to be used?

**Comment by salvador-blanco** [comment]
Would it be possible to get pixel error metrics?

**Comment by ganler** [comment]
@Gyx-One Hi Yixiao, please take a look.

**Comment by Gyx-One** [comment]
Hello! sorry to response after so long because I've been tough these days...
the function **evaluate** have a paramter **total_eval_num** which determines how many images will be used in evaluation(I set this paramter for debugging), and its default value is **30**, so maybe that's the reason in your case that not all the images are used in evaluation.
I have already change the default value up to **10000** in my next pull request, so this won't happen any more. :)
Thanks for using our library, if you have any further qustions, wecolme to ask.

**Comment by salvador-blanco** [comment]
Thank you that worked
